### ISSUE TITLE
read /dev/ptmx: input/output error in output since d1c5490cec2a1506fb6f5a474cb9cd106edef5e6

### ISSUE THREAD

**Issue by F21** [unchartedsoftware/witch#4]
I am running witch in a Go docker container which is started using docker-compose which runs my Go tests.

Since d1c5490cec2a1506fb6f5a474cb9cd106edef5e6, I am seeing this output at the end of the output each time the tests finish running: `read /dev/ptmx: input/output error`

**Comment by F21** [comment]
This isn't a problem with witch, but rather `/dev/ptmx` is removed in the latest build of the Golang alpine container (`1.12.7-alpine`).

**Comment by F21** [comment]
Rolling back to 33a995176f45a86ef9c4a2a02664650c80f5d231 works. 

May be related to https://github.com/creack/pty/issues/21, but in the container, I can see that `/dev/ptmx exists`.

**Comment by F21** [comment]
This is a reply from the maintainer of pty regarding the possible cause: https://github.com/creack/pty/issues/21#issuecomment-513069505

**Comment by kbirk** [comment]
Thanks for looking into this. For now it will simply ignore the error if it is a `read /dev/ptmx: input/output error"` as it seems like the simplest solution at the time.
